version: "3.8"
services:

     deeplandforms:
        image: deeplandforms
        container_name: deeplandforms
        init: true
        build:
            context: ./
            dockerfile: DeepLandforms.Dockerfile
        shm_size: 8gb
        env_file: ./.env
        user: user
        ports:
              - ${DL_JUPYTER_PORT}:${DL_JUPYTER_PORT}
        volumes:
              - ${DATA_DIR}:/home/user/data
              - ${DL_DIR}:/home/user/DeepLandforms
        command:
            [
                "jupyter",
                "lab",
                "--ip=0.0.0.0",
                "--no-browser",
                "--port=${DL_JUPYTER_PORT}",
#                "--notebook-dir=${JUPYTER_DIR}",
            ]
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: all
                capabilities: [gpu,utility,compute]
     tensorboard:
          image: tensorboard
          container_name: tensorboard
          build:
               context: ./
               dockerfile: tensorboard.Dockerfile
          ports:
               - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
          volumes:
               - ${DATA_DIR}/train:/logdir
          command:
            [
                "tensorboard",
                "--logdir=/logdir",
                "--port=${TENSORBOARD_PORT}",
                "--host=0.0.0.0",
            ]
     ipu:
        image: ipu
        container_name: ipu
        init: true
        build:
            context: ./
            dockerfile: IPU.Dockerfile
        env_file: ./.env
        user: jovyan
        ports:
              - ${IPU_JUPYTER_PORT}:${IPU_JUPYTER_PORT}
        volumes:
              - ${IPU_DIR}:/home/jovyan/IPU
              - ${DATA_DIR}:/home/jovyan/data
        command:
            [
                "jupyter",
                "lab",
                "--ip=0.0.0.0",
                "--no-browser",
                "--port=${IPU_JUPYTER_PORT}",
#                "--notebook-dir=${JUPYTER_DIR}",
            ]

     labelme:
        image: labelme
        container_name: labelme
        build:
            context: ./
            dockerfile: labelme.Dockerfile
        user: user
        environment:
               - DISPLAY=${DISPLAY}
        volumes:
               - ${DATA_DIR}:/home/user/data
               - /tmp/.X11-unix:/tmp/.X11-unix
        command:
            ["labelme"]
