version: "3.8"
services:
     tensorboard:
          image: tensorboard
          build:
               context: ./
               dockerfile: tensorboard.Dockerfile
          ports:
               - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
          volumes:
               - ${DATA_DIR}/train:/mnt/logdir
          command:
            [
                "tensorboard",
                "--logdir=${TENSORBOARD_DIR}",
                "--port=${TENSORBOARD_PORT}",
                "--host=0.0.0.0",
            ]

     deeplandforms:
        image: deeplandforms
        init: true
        build:
            context: ./
            dockerfile: DeepLandforms.Dockerfile

        env_file: ./.env
        user: user
        ports:
              - ${JUPYTER_PORT}:${JUPYTER_PORT}
        volumes:
              - ${DATA_DIR}:/home/user/data
              - ${DL_DIR}:/home/user/DeepLandforms
              - ${MODEL_DIR}:/home/user/pre-trained_model
        command:
            [
                "jupyter",
                "lab",
                "--ip=0.0.0.0",
                "--no-browser",
                "--port=${JUPYTER_PORT}",
#                "--notebook-dir=${JUPYTER_DIR}",
            ]
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: all
                capabilities: [gpu,utility,compute]
     labelme:
        image: labelme
        build:
            context: ./
            dockerfile: labelme.Dockerfile
        user: user
        environment:
               - DISPLAY=${DISPLAY}
        volumes:
               - ${DATA_DIR}:/home/user/data
               - /tmp/.X11-unix:/tmp/.X11-unix
        command:
            ["labelme"]
